all:
	gcc src/main.c src/bezier.c src/area.c src/utils.c src/graphics.c -o splines.exe -lmingw32 -lSDL2main -lSDL2 -lm

linux:
	gcc src/main.c src/bezier.c src/area.c src/utils.c src/graphics.c -o splines -lSDL2main -lSDL2 -lm
